# Generated by Django 3.1.7 on 2021-07-10 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_hospital', '0003_register_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='unique_id',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='unique_id',
            new_name='uid',
        ),
    ]
